[package]
name = "virtual-dom"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "Virtual DOM"
license = "LGPL-3.0"

[lib]
name = "virtual_dom"
crate-type = ["cdylib"]

[dependencies]
